apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-application
  namespace: {{ .Release.Namespace }}
data:
  logstash.conf: |-
    input {
      tcp {
        port => 5044
        codec => "json"
      }
    }
    output {
      elasticsearch {
        hosts => "elasticsearch-logging:9200"
        index => "logstash-%%{+YYYY.MM.dd}"
        sniffing => false
      }
    }
  logstash.yml: |-
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    xpack.monitoring.enabled: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-application
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels: {app: logstash-application}
  template:
    metadata:
      labels:
        app: logstash-application
    spec:
      containers:
      - image: {{ .Values.logstashImage }}
        name: logstash-application
        ports:
        - name: logstash
          containerPort: 5044
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
          readOnly: true
        - name: pipeline
          mountPath: /usr/share/logstash/pipeline
          readOnly: true
        args:
        - -f
        - /usr/share/logstash/pipeline/logstash.conf
        resources:
          limits:
            memory: {{ .Values.logstashMemoryLimit }}
            cpu: "200m"
          requests:
            memory: {{ .Values.logstashMemoryLimit }}
            cpu: "200m"
      volumes:
      - name: pipeline
        configMap:
          name: logstash-application
          items:
          - key: logstash.conf
            path: logstash.conf
      - name: config
        configMap:
          name: logstash-application
          items:
          - key: logstash.yml
            path: logstash.yml
