apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: cca-elk
provisioner: {{ .Values.storageclassProvisioner }}
parameters:
    type: gp2
reclaimPolicy: Retain
mountOptions:
    - debug
volumeBindingMode: Immediate
