{{ if .Values.useNginxIngress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ckan-ingress-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  {{ if .Values.nginxIngressTlsSecret }}
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: {{ .Values.nginxIngressTlsSecret }}
  {{ end }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - backend:
          serviceName: ckan
          servicePort: 5000
        path: /(.*)
{{ end }}
