{{ if not .Values.centralizedInfraOnly }}
{{ if .Values.usePersistentVolumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Namespace }}-ckan
spec:
  storageClassName: {{ .Values.ckanStorageClassName }}
  accessModes:
    - {{ .Values.diskAccessMode | default "ReadWriteMany" }} 
  resources:
    requests:
      storage: 1Mi
{{ end }}
{{ end }}
