{{ if not .Values.centralizedInfraOnly }}
{{ if not .Values.useCentralizedInfra }}
apiVersion: apps/v1beta1
kind: Service
metadata:
  name: datastore-db
spec:
  selector:
    app: datastore-db
  ports:
  - name: "5432"
    port: 5432
{{ end }}
{{ end }}
