{{ if .Values.enableGiftless }}
apiVersion: v1
kind: Secret
metadata:
  name: jwt-keys
data:
  jwt-rs256.key: {{ .Values.CkanAuthzJwtKey }}
  jwt-rs256.key.pub: {{ .Values.CkanAuthzJwtKeyPub }}
{{ end }}
