{{ if .Values.enableHarvesterNG }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata: {name: harvester-db}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels: {app: harvester-db}
    spec:
      containers:
      - name: postgres
        image: postgres:9.6
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "airflow"
        - name: POSTGRES_USER
          value: "airflow"
        - name: POSTGRES_DB
          value: "airflow"
        {{ if .Values.harvesterDbResources }}
        resources: {{ .Values.harvesterDbResources }}
        {{ end }}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: ckan-data
          subPath: ckan-harvester-db
      volumes:
      - name: ckan-data
      {{ if .Values.usePersistentVolumes }}
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-harvester-db
      {{ else }}
        hostPath:
          path: /var/ckan-cloud-{{ .Release.Namespace }}
          type: DirectoryOrCreate
      {{ end }}
{{ end }}