{{ if .Values.enableHarvesterNG }}
apiVersion: apps/v1
kind: Deployment
metadata: {name: harvester}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels: {app: harvester}
  template:
    metadata:
      labels: {app: harvester}
    spec:
      serviceAccountName: ckan-{{ .Release.Namespace }}-operator
      initContainers:
        - name: secrets
          image: {{ .Values.ckanOperatorImage | quote }}
          command:
          - bash
          - "-c"
          - |
            ./cca-operator.sh initialize-ckan-env-vars {{ .Values.envVarsSecretName | quote }} &&\
            ./cca-operator.sh initialize-ckan-secrets {{ .Values.envVarsSecretName | quote }} \
                                                      {{ .Values.ckanSecretName | quote }} &&\
            ./cca-operator.sh get-ckan-secrets {{ .Values.ckanSecretName | quote }} /etc/ckan-conf/secrets/secrets.sh &&\
            echo ckan secrets initialized successfully && exit 0
            echo failed to initialize, waiting 1 hour before exiting && sleep 3600 && exit 1
          env:
          - name: CKAN_CLOUD_INSTANCE_ID
            value: {{ .Values.ckanCloudInstanceId | quote }}
          - name: CKAN_CLOUD_POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: {{ .Values.centralizedSecretName | quote }}
                key: "POSTGRES_HOST"
          - name: CKAN_CLOUD_POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.centralizedSecretName | quote }}
                key: "POSTGRES_USER"
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.centralizedSecretName | quote }}
                key: "POSTGRES_PASSWORD"
          - name: CKAN_CLOUD_SOLR_HOST
            value: {{ .Values.centralizedSolrHost | default "solr.ckan-cloud" | quote }}
          - name: CKAN_CLOUD_SOLR_PORT
            value: {{ .Values.centralizedSolrPort | default "8983" | quote }}
          volumeMounts:
          - name: harvester-secrets
            mountPath: /etc/ckan-conf/secrets
      containers:
      - name: harvester
        image: {{ .Values.harvesterImage | quote }}
        env:
        - name: LOAD_EX
          value: "n"
        - name: EXECUTOR
          value: Local
        - name: POSTGRES_USER
          value: airflow
        - name: POSTGRES_PASSWORD
          value: airflow
        - name: POSTGRES_DB
          value: airflow
        - name: POSTGRES_HOST
          value: harvester-db
        - name: CKAN_API_KEY
          value: READ_FROM_DB
        - name: CKAN_BASE_URL
          value: http://ckan:5000
        - name: CKAN_VALID_USER_ID
          value: admin
        - name: HARVESTER_APP_PATH
          value: /app
        - name: AIRFLOW__WEBSERVER__WEB_SERVER_PORT
          value: "8082"
        - name: AIRFLOW__WEBSERVER__BASE_URL
          value: https://my_host/airflow
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: /app/automate-tasks/airflow/dags
        - name: AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT
          value: "180"
        - name: AIRFLOW__CORE__PARALLELISM
          value: "3"
        - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
          value: "False"
        resources: {{ .Values.harvesterResources }}
        volumeMounts:
        - name: harvester-secrets
          mountPath: /etc/ckan-conf/secrets
          readOnly: true
        ports:
        - containerPort: 8082
      volumes:
        - name: harvester-secrets
          emptyDir: {}
      

{{ end }}