{{ if not .Values.centralizedInfraOnly }}
{{ if .Values.usePersistentVolumes }}
apiVersion: apps/v1beta1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Namespace }}-jobs-db
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.jobsDbPersistentDiskSizeGB }}G
{{ end }}
{{ end }}
