{{ if not .Values.centralizedInfraOnly }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: {{ .Values.nginxReplicas | default "2" }}
  selector:
    matchLabels: {app: nginx}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: nginx
        image: {{ .Values.nginxImage | default "nginx:1.17-alpine" | quote }}
        ports:
        - containerPort: 8080
        {{ if .Values.nginxResources }}
        resources: {{ .Values.nginxResources }}
        {{ end }}
        volumeMounts:
        - name: nginx-configuration
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-configuration
        configMap:
          name: nginx
{{ end }}