{{ if not .Values.centralizedInfraOnly }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  default.conf: |
    proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=cache:30m max_size=250m;
    proxy_temp_path /tmp/nginx_proxy 1 2;
    server {
        listen 8080;
        server_name _;
        client_max_body_size 1000M;
{{ if .Values.enableHarvesterNG }}
        location /airflow/ {
            proxy_pass http://harvester:8082;

            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host $host;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
{{ end }}

{{ if .Values.enableGiftless }}
        location /{{ .Values.giftlessProxyPrefix | default giftless | quote }}/ {
            proxy_pass http://giftless:5000/;
            proxy_set_header X-Forwarded-Prefix /{{ .Values.giftlessProxyPrefix | default giftless | quote }};
        }
{{ end }}
        location / {
            proxy_pass http://ckan:5000;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host $http_host;
            proxy_cache cache;
            proxy_cache_bypass $cookie_auth_tkt;
            proxy_no_cache $cookie_auth_tkt;
            proxy_cache_valid 30m;
            proxy_cache_key $http_host$scheme$proxy_host$request_uri;
            # In emergency comment out line to force caching
            # proxy_ignore_headers X-Accel-Expires Expires Cache-Control;
        }
    }
{{ end }}
