{{ if not .Values.centralizedInfraOnly }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels: {app: redis}
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        {{ if .Values.redisResources }}
        resources: {{ .Values.redisResources }}
        {{ end }}
{{ end }}