{{ if not .Values.useCentralizedInfra }}
{{ if .Values.usePersistentVolumes }}
{{ if not .Values.solrDisabled }}
apiVersion: apps/v1beta1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Namespace }}-solr
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.solrPersistentDiskSizeGB }}G
{{ end }}
{{ end }}
{{ end }}
